# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IncidentHeatGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IncidentHeat(object):
    def setupUi(self, IncidentHeat):
        IncidentHeat.setObjectName("IncidentHeat")
        IncidentHeat.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(IncidentHeat)
        self.centralwidget.setObjectName("centralwidget")
        self.h = QtWidgets.QSpinBox(self.centralwidget)
        self.h.setGeometry(QtCore.QRect(290, 40, 91, 21))
        self.h.setObjectName("h")
        self.r = QtWidgets.QSpinBox(self.centralwidget)
        self.r.setGeometry(QtCore.QRect(290, 60, 91, 21))
        self.r.setObjectName("r")
        self.emissivity = QtWidgets.QSpinBox(self.centralwidget)
        self.emissivity.setGeometry(QtCore.QRect(290, 90, 91, 21))
        self.emissivity.setObjectName("emissivity")
        self.absorptivity = QtWidgets.QSpinBox(self.centralwidget)
        self.absorptivity.setGeometry(QtCore.QRect(290, 110, 91, 21))
        self.absorptivity.setObjectName("absorptivity")
        self.specificHeat = QtWidgets.QSpinBox(self.centralwidget)
        self.specificHeat.setGeometry(QtCore.QRect(290, 130, 91, 21))
        self.specificHeat.setObjectName("specificHeat")
        self.density = QtWidgets.QSpinBox(self.centralwidget)
        self.density.setGeometry(QtCore.QRect(290, 160, 91, 21))
        self.density.setObjectName("density")
        self.initialtemperature = QtWidgets.QSpinBox(self.centralwidget)
        self.initialtemperature.setGeometry(QtCore.QRect(290, 190, 91, 21))
        self.initialtemperature.setObjectName("initialtemperature")
        self.eclipselength = QtWidgets.QSpinBox(self.centralwidget)
        self.eclipselength.setGeometry(QtCore.QRect(290, 220, 91, 21))
        self.eclipselength.setObjectName("eclipselength")
        self.period = QtWidgets.QSpinBox(self.centralwidget)
        self.period.setGeometry(QtCore.QRect(290, 240, 91, 21))
        self.period.setObjectName("period")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 30, 261, 241))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 300, 161, 51))
        self.pushButton.setObjectName("pushButton")
        IncidentHeat.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(IncidentHeat)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        IncidentHeat.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(IncidentHeat)
        self.statusbar.setObjectName("statusbar")
        IncidentHeat.setStatusBar(self.statusbar)

        self.retranslateUi(IncidentHeat)
        QtCore.QMetaObject.connectSlotsByName(IncidentHeat)

    def retranslateUi(self, IncidentHeat):
        _translate = QtCore.QCoreApplication.translate
        IncidentHeat.setWindowTitle(_translate("IncidentHeat", "MainWindow"))
        self.textBrowser.setHtml(_translate("IncidentHeat", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">altitude of spacecraft h</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">radius of cubesat r (m)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">emissivity </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">absorptivity</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">specfic heat</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">density</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">initial temperature</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">eclipse length</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">period</span></p></body></html>"))
        self.pushButton.setText(_translate("IncidentHeat", "Plot"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IncidentHeat = QtWidgets.QMainWindow()
    ui = Ui_IncidentHeat()
    ui.setupUi(IncidentHeat)
    IncidentHeat.show()
    sys.exit(app.exec_())
